const colors = {
  dark: {
    text: "#FFFFFF",
    tint: "#2775FF",
    background: "#0A0E17",
    foreground: "#FFFFFF",
    card: "#131824",
    cardForeground: "#FFFFFF",
    primary: "#2775FF",
    primaryForeground: "#FFFFFF",
    secondary: "#1A2235",
    secondaryForeground: "#FFFFFF",
    muted: "#1E2738",
    mutedForeground: "#8A9BB0",
    accent: "#00C2A8",
    accentForeground: "#000000",
    destructive: "#FF5F6D",
    destructiveForeground: "#FFFFFF",
    border: "#1E2738",
    input: "#1A2235",
    positive: "#00C2A8",
    negative: "#FF5F6D",
  },
  light: {
    text: "#0A0E17",
    tint: "#2775FF",
    background: "#F0F4FF",
    foreground: "#0A0E17",
    card: "#FFFFFF",
    cardForeground: "#0A0E17",
    primary: "#2775FF",
    primaryForeground: "#FFFFFF",
    secondary: "#E8EDF5",
    secondaryForeground: "#0A0E17",
    muted: "#E8EDF5",
    mutedForeground: "#6B7A99",
    accent: "#00C2A8",
    accentForeground: "#FFFFFF",
    destructive: "#FF4444",
    destructiveForeground: "#FFFFFF",
    border: "#D0D8EE",
    input: "#E8EDF5",
    positive: "#00B894",
    negative: "#FF4444",
  },
  radius: 14,
};

export default colors;
